Add files via upload
for some reason i cant commit to github at the school computer either?? it shows this message: 

 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/azizamadai/quiz.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

i should probably ask for help (but i am too anxious to) because i must've made some big mistake early on and now my github repository is all over the place! errr....

in this commit, i added the global variable, "score" (but it is essentially useless right now),  and defined my own function successfully.